### ISSUE TITLE
No objects to concatenate

### ISSUE THREAD

**Issue by joonjeon** [pixelite1201/agora_evaluation#22]
Hi! I attempted to run the following:

```
evaluate_agora --pred_path ~/data/EHF/meshes_aligned/ --result_savePath results/ --imgFolder ~/data/EHF/images/ --modelFolder ./data/models/smplx/
```

However, this runs into the error as follows:
```
Traceback (most recent call last):
  File "/home/joon_local/miniconda3/envs/pytorch/bin/evaluate_agora", line 33, in <module>
    sys.exit(load_entry_point('agora-evaluation', 'console_scripts', 'evaluate_agora')())
  File "/home/joon_local/agora_evaluation/agora_evaluation/cli.py", line 30, in evaluate_agora
    run_evaluation(sys.argv[1:])
  File "/home/joon_local/agora_evaluation/agora_evaluation/evaluate_agora.py", line 287, in run_evaluation
    error_df = pandas.concat(error_df_list)
  File "/home/joon_local/miniconda3/envs/pytorch/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 372, in concat
    op = _Concatenator(
  File "/home/joon_local/miniconda3/envs/pytorch/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 429, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

Any ideas on why this is happening?

Thanks in advance.

**Comment by Z-mingyu** [comment]
Hi, I encountered the same problem as you. How did you solve it?
